FROM amazon/aws-lambda-python:latest
LABEL authors="darylmathison"

COPY requirements.txt .
RUN dnf -y update && \
    dnf -y install wget git gcc gcc-c++ make automake autoconf libtool zip tar && \
    dnf clean all && \
    mkdir -p ./test && pip3 install -r requirements.txt  && \
    pip3 install pytest flake8
COPY data/stock_model.pickle ${LAMBDA_TASK_ROOT}
COPY src/main.py ${LAMBDA_TASK_ROOT}
COPY test ${LAMBDA_TASK_ROOT}/test

WORKDIR ${LAMBDA_TASK_ROOT}
ENTRYPOINT [ "" ]