name: Update Model

on: workflow_dispatch

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: set GH_TOKEN
        if: env.GH_TOKEN == ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "GH_TOKEN=${GITHUB_TOKEN}" >> $GITHUB_ENV
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
          token: ${{ env.GH_TOKEN }}
      - name: pull in requirements
        run: pip3 install -r requirements.txt
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Create a branch
        run: git checkout -b update-model-${{ steps.date.outputs.date }}
      - name: Train the model
        run: python src/train.py
      - name: Add, Commit
        run: |
          git config --global user.email "${{ vars.email }}"
          git config --global user.name "${{ vars.name }}"
          git commit -a -m'update the model ${{ steps.date.outputs.date }}'
      - name: Push
        run: git push --set-upstream origin update-model-${{ steps.date.outputs.date }}