name: Update Model

on: workflow_dispatch

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull in requirements
        run: pip3 install -r requirements.txt
      - name: Train the model
        run: cd src; python train.py
