name: Update Model

on: workflow_dispatch

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: 'update-model'
      - name: Set git Username
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: pull in requirements
        run: pip3 install -r requirements.txt
      - name: Train the model
        run: python src/train.py
      - name: Add, Commit
        run: git commit -a -m'update the model ${{ steps.date.outputs.date }}'
      - name: Push
        run: |
          git push