name: Update Model

on: workflow_dispatch

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: pull in requirements
        run: pip3 install -r requirements.txt
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Create a branch
        run: git checkout update-model
      - name: Train the model
        run: python src/train.py
      - name: Add, Commit
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -a -m'update the model ${{ steps.date.outputs.date }}'
      - name: Push-Action
        uses: Minionguyjpro/Push-Action@1.0.0